"""Research narratives for the five companion papers, grounded in their manuscripts."""
def B(ko,en):return {'ko':ko,'en':en}
def block(ko,en,kbody,ebody,ref):return {'title':B(ko,en),'body':B(kbody,ebody),'ref':ref}
D={}
D['velocity-reuse']={
'problem':[
block('생성 단계 내부의 반복 계산에 주목','Focus on repetition inside action generation','Flow Matching 기반 VLA는 image·language conditioning 이후에도 여러 Euler step을 거쳐 action chunk를 생성합니다. Vision-language backbone을 줄이는 방법과 별개로, action generator 자체의 반복 연산을 줄이는 문제에 집중했습니다.','A flow-matching VLA generates an action chunk through multiple Euler steps after processing image and language conditioning. This work focuses on reducing repeated computation in the action generator itself, separately from accelerating the vision-language backbone.','§1'),
block('Internal feature 대신 output velocity를 재사용할 수 있을까?','Can output velocity be reused instead of internal features?','모델 구조에 의존하는 intermediate feature 대신, generator가 최종적으로 출력하는 velocity의 중복성을 살폈습니다. 먼저 인접 step 사이에서 velocity의 방향과 크기가 얼마나 변하는지 측정하고, 재사용 가능한지를 실험으로 확인하는 문제로 정의했습니다.','Rather than caching architecture-specific intermediate features, the study examines redundancy in the generator’s output velocity. It first measures changes in direction and magnitude across adjacent steps, then tests whether these outputs can be reused.','§2.2'),
block('관찰을 여러 모델과 조건에서 확인','Check the observation across models and conditions','LIBERO 네 suite에서 π0.5의 인접 output cosine similarity는 평균 0.9997, norm ratio는 0.9984였습니다. GR00T-N1.7에서도 높은 유사도를 확인했습니다. 이 관찰을 근거로 일정 간격으로 velocity를 갱신하는 규칙을 구성하고, 성공률이 유지되는 범위를 평가했습니다.','Across four LIBERO suites, π0.5 has a mean adjacent-output cosine similarity of 0.9997 and norm ratio of 0.9984. GR00T-N1.7 also exhibits high similarity. These observations motivate refreshing velocity at fixed intervals and evaluating how aggressively reuse can be applied while retaining task success.','Table 1')],
'method':[
block('Output refresh와 Euler update','Output refreshes and Euler updates','첫 generation step에서 velocity를 계산하고 이후 k step마다 갱신합니다. 중간 step에서는 가장 최근 velocity를 사용해 Euler state update를 수행합니다. N=10, k=5이면 action generator forward pass는 10회에서 2회로 줄어듭니다.','Compute velocity at the first generation step and refresh it every k steps. Intermediate Euler state updates use the most recent velocity. For N=10 and k=5, action-generator forward passes decrease from ten to two.','§2.3'),
block('성공률과 inference latency의 동시 검증','Evaluate task success alongside inference latency','환경 reset과 초기 action noise를 맞춘 Paired 조건, 제어 step마다 초기 noise를 새로 추출하는 Random 조건을 구분했습니다. 성공률은 3개 seed에서 평가하고, latency는 A6000에서 30회 warm-up과 100회 반복으로 측정했습니다.','Separate a Paired protocol with matched environment resets and initial action noise from a Random protocol with fresh initial noise at each control step. Evaluate success over three seeds and measure latency on an A6000 with 30 warm-up runs and 100 timed repetitions.','§3.1 · Table 2, Table 3, Table 4')],
'results_intro':B('재사용 간격 k를 늘렸을 때 성공률과 latency가 어떻게 변하는지 비교합니다. π0.5는 Paired·Random 조건을 구분하며, 아래 latency는 이 IEIE 논문의 실험값입니다.','Compare task success and latency as the reuse interval k increases. π0.5 is evaluated under separate Paired and Random protocols. The latency values below are from this IEIE paper.'),
'caption':B('그림 1. 속도 재사용 방법(π0.5). τ=0에서 초기 속도 계산 후 τ가 kδ의 배수가 될 때만 속도 재계산. 나머지 시간에서도 오일러 업데이트는 수행되며, 가장 최근에 계산된 속도를 재사용.','Figure 1. Velocity reuse (π0.5). Compute the initial velocity at τ=0 and recompute it only when τ is a multiple of kδ. Euler updates continue at the remaining steps using the most recently computed velocity.'),
'metric_refs':['Table 4 (π0.5 · k=10)','Table 4 (π0.5 · k=10)','Table 2 (π0.5 · LIBERO)']}
D['star']={
'problem':[
block('CCTV에서 사고 단서는 짧고 국소적이다','Accident evidence in CCTV is brief and localized','사고 탐지는 사고 시점·위치·유형을 함께 예측해야 합니다. 하지만 저조도·날씨·카메라 시점으로 appearance가 불명확하고, 사고 단서는 긴 영상의 짧은 구간과 작은 영역에만 나타납니다. 모든 정보를 한 번에 추론하기보다 관련 맥락을 먼저 좁히는 문제로 접근했습니다.','Accident detection requires predicting time, location, and collision type together. Yet lighting, weather, and camera viewpoint can degrade appearance, while decisive evidence occupies only a short interval and a localized region. This motivates narrowing the relevant context before asking for all three predictions.','§1'),
block('RGB가 모호할 때 motion을 보조 단서로 사용','Use motion cues when RGB appearance is ambiguous','Optical flow의 급감속·궤적 이탈 같은 motion anomaly는 RGB appearance와 다른 정보를 제공합니다. 이를 사고를 확정하는 rule이 아니라 VLM이 집중할 후보 시간 구간으로 바꾸고, 사고 시점을 먼저 찾도록 구성했습니다.','Optical-flow anomalies such as abrupt deceleration and trajectory deviation provide information distinct from RGB appearance. The pipeline turns them into candidate time windows that guide the VLM, rather than rules that directly declare an accident.','§2.2'),
block('모든 과업을 같은 방식으로 학습하지 않기','Do not adapt every task in the same way','합성 데이터의 class imbalance와 scene bias를 고려해, geometric localization과 collision-type classification을 구분했습니다. 시간·공간 과업에는 LoRA를 적용하고 유형 분류는 zero-shot prior를 유지하는 전략을 과업별 ablation으로 검증했습니다.','Class imbalance and scene bias in synthetic data motivate separating geometric localization from collision-type classification. Temporal and spatial tasks use LoRA, while type classification retains the backbone’s zero-shot prior. Task-specific ablations evaluate this adaptation strategy.','§2.4 · Table 4')],
'method':[
block('Motion-guided temporal localization','Motion-guided temporal localization','MEMFOF optical flow에서 추출한 motion event의 구간과 severity를 candidate cue로 구성합니다. 8 FPS 영상과 이 cue를 VLM에 제공해 사고 시점 t̂를 예측합니다.','Form candidate cues from the time windows and severity of motion events extracted with MEMFOF optical flow. Provide these cues with video sampled at 8 FPS to predict the accident time t̂.','§2.2'),
block('사고 중심의 짧은 영상으로 후속 추론','Use an accident-centered clip for downstream inference','예측한 t̂를 중심으로 6초 영상을 추출하고, 동일한 clip으로 spatial localization과 collision-type classification을 수행합니다. 위치는 예측 bounding box의 중심으로 표현합니다.','Extract a six-second clip centered on t̂ and use it for both spatial localization and collision-type classification. Represent the accident location by the center of the predicted bounding box.','§2.1–2.3 · Figure 2'),
block('Selective LoRA','Selective LoRA','하나의 Qwen3.5-9B backbone을 공유하면서 temporal·spatial LoRA를 각각 학습합니다. Collision type은 전용 LoRA 없이 zero-shot으로 분류합니다.','Share one Qwen3.5-9B backbone with separately trained temporal and spatial LoRA adapters. Classify collision type zero-shot, without a dedicated LoRA adapter.','§2.3–2.4')],
'results_intro':B('전체 pipeline 비교에 더해, temporal crop과 과업별 LoRA의 효과를 분리해 확인합니다. T·S·C는 각각 temporal similarity, spatial similarity, collision-type accuracy이고, ACCS는 통합 점수입니다.','In addition to comparing full pipelines, separate ablations evaluate temporal cropping and task-specific LoRA. T, S, and C denote temporal similarity, spatial similarity, and collision-type accuracy; ACCS is the unified score.'),
'caption':B('Figure 2. Overview of the STAR pipeline. Optical-flow-based candidate cues guide Temporal Localization to predict t̂. The trimmed video Vₜ̂ is then used for Spatial Localization and Collision Type Classification to produce ŷ = (t̂, p̂, ĉ).','Figure 2. Overview of the STAR pipeline. Optical-flow-based candidate cues guide Temporal Localization to predict t̂. The trimmed video Vₜ̂ is then used for Spatial Localization and Collision Type Classification to produce ŷ = (t̂, p̂, ĉ).'),
'metric_refs':['Table 2 (ACCS)','Table 2 (Temporal)','Table 2 (Spatial)']}
D['navila-patch']={
'problem':[
block('시각 모델의 취약성이 주행 행동으로 이어지는가?','Can a visual-model vulnerability alter navigation actions?','Vision-language navigation은 관측 영상과 언어 지시를 실제 이동으로 연결합니다. 따라서 입력 교란을 단순한 인식 오류가 아니라 잘못된 행동과 경로로 이어질 수 있는 문제로 보았습니다. 자연어 action을 생성하는 VLA의 취약성을 주행 성공률과 경로 효율로 평가했습니다.','Vision-language navigation turns visual observations and instructions into movement. Input perturbations therefore matter beyond recognition errors: they can alter actions and paths. The study evaluates the vulnerability of a natural-language-action VLA through navigation success and path efficiency.','§1'),
block('Natural-language action의 구조에서 공격 목표를 정의','Define the target from the natural-language action structure','모델이 생성한 문장은 keyword parsing을 거쳐 이동 명령으로 변환됩니다. 이 구조에 맞춰 기존 action format은 유지하되, 행동 유형·방향·제어 값이 다른 target action을 정의했습니다.','Generated sentences are converted into movement commands through keyword parsing. Targets are defined to preserve the expected action format while changing the action type, direction, or control value.','§2.1'),
block('가림과 학습된 교란의 효과를 구분','Distinguish occlusion from learned perturbations','Black patch와 Gaussian-initialized patch를 비교 조건으로 두어 단순한 가림·noise 효과를 분리했습니다. 이어 patch 크기와 노출 구간을 바꾸면서, 모델의 취약성이 어떤 조건에서 주행 성능 저하로 이어지는지 살폈습니다.','Black and Gaussian-initialized patches serve as controls for occlusion and unoptimized noise. Separate size and exposure studies examine the conditions under which the learned perturbation degrades navigation.','§3.2–3.4 · Table 1, Table 2, Table 3')],
'method':[
block('Policy는 고정하고 patch만 최적화','Optimize the patch while keeping the policy fixed','현재 관측 1장과 과거 관측 7장에 patch를 적용하고, rotation·shear를 포함한 EOT로 관측 변화를 반영합니다. 모델 파라미터는 고정한 채 target action에 대한 손실로 patch를 학습합니다.','Apply the patch to the current observation and seven historical observations, using EOT with rotation and shear to model input variation. Keep model parameters fixed and optimize only the patch against the target action.','§2.2'),
block('Action format을 유지하며 학습 신호를 집중','Focus the objective while retaining the action format','공통 문장과 변경되지 않은 토큰은 손실에서 제외하고, target action에 해당하는 토큰에 학습 신호를 집중합니다. Stop target에는 unlikelihood loss를 함께 사용합니다.','Exclude shared sentence structure and unchanged tokens from the objective, focusing the learning signal on target-action tokens. Use an additional unlikelihood loss for the Stop target.','§2.2'),
block('주행 성능으로 평가','Evaluate navigation behavior','R2R-CE와 RxR-CE Val-Unseen의 VLN-CE 시뮬레이션에서 NE·OS·SR·SPL을 측정합니다. 전체 노출, 초기 10회 노출, 주기적 노출은 별도의 비교 조건입니다.','Measure NE, OS, SR, and SPL in VLN-CE simulation on R2R-CE and RxR-CE Val-Unseen. Full, initial-ten-step, and periodic exposure are evaluated as separate conditions.','§3.1, §3.4')],
'results_intro':B('Patch의 생성 방식·크기·노출 조건을 나누어 비교합니다. NE는 목표까지의 거리이며 낮을수록 좋고, OS·SR·SPL은 성공과 경로 효율을 나타내며 높을수록 좋습니다.','Compare patch construction, size, and exposure separately. NE measures distance to the goal and is lower-is-better; OS, SR, and SPL measure success and path efficiency and are higher-is-better.'),
'caption':B('그림 1. 적대적 패치 생성과 적대적 공격 수행 과정','Figure 1. Adversarial patch generation and attack procedure.'),
'metric_refs':['Table 1 (R2R-CE)','Table 1 (RxR-CE)','§3.3 · Figure 5']}
D['lift3d-film']={
'problem':[
block('3D geometry에 과업의 목표를 더하기','Add task intent to 3D geometry','Point cloud는 공간 구조를 표현하지만, 같은 물체를 어떻게 조작해야 하는지는 과업의 목표에 따라 달라집니다. Lift3D의 3D representation learning에 language conditioning을 추가해 목표를 visual feature에 반영하는 문제로 정의했습니다.','Point clouds represent geometry, but the intended interaction with an object depends on the task. The research question is whether adding language conditioning to Lift3D’s 3D representation learning can make visual features reflect that intent.','§1–2'),
block('텍스트를 붙이는 대신 feature를 조정','Condition the features rather than only append text','FiLM이 language embedding으로 feature의 scale과 shift를 조절한다는 점에 주목했습니다. 이를 Transformer의 explicit 3D representation 학습 단계에 결합해, 객체의 geometry와 과업 목표를 함께 다루도록 했습니다.','FiLM uses a language embedding to scale and shift features. Integrating it into the Transformer’s explicit 3D representation learning stage makes it possible to condition visual features on both geometry and task intent.','§2.3'),
block('성능이 떨어진 과업에서 지시문을 다시 검토','Revisit the instruction where performance drops','기본 지시문에서는 8개 중 7개 과업이 개선되었지만 sweep into는 74%에서 72%로 하락했습니다. 이를 계기로 객체·동작·위치 관계를 구체화한 지시문을 구성하고 네 과업을 추가 평가했습니다. Sweep into는 이 조건에서 82%로 높아졌습니다.','Basic instructions improve seven of eight tasks, but sweep into drops from 74% to 72%. This motivates more explicit descriptions of objects, actions, and spatial relations, followed by additional evaluation on four tasks. Sweep into reaches 82% with the detailed instruction.','Table 1, Table 2')],
'method':[
block('FiLM 기반 language conditioning','FiLM-based language conditioning','CLIP text encoder의 language embedding을 MLP 기반 FiLM generator에 넣어 γ와 β를 얻습니다. H′ = γ ⊙ H + β로 visual feature를 조정하고, CLIP-ViT의 매 세 번째 block에 적용합니다.','Map a CLIP text embedding through an MLP-based FiLM generator to obtain γ and β. Modulate visual features as H′ = γ ⊙ H + β at every third CLIP-ViT block.','§2.3 · Equations 1–2'),
block('기존 3D 학습 구조에 통합','Integrate into the existing 3D learning pipeline','Lift3D의 두 번째 학습 단계에 language conditioning을 결합하고 LoRA로 fine-tuning합니다. 생성된 3D feature와 robot state를 policy head에 입력해 위치 변화와 gripper 상태를 예측합니다.','Add language conditioning to Lift3D’s second training stage and fine-tune with LoRA. The policy head uses the resulting 3D features and robot state to predict position changes and gripper state.','§2 · Figure 1')],
'results_intro':B('Meta-World 8개 과업의 기본 지시문 결과와, 네 과업에 대해 보고된 상세 지시문 결과를 구분해 표시합니다. 과업당 50회 평가했으며, 아래에서 지시문 구체성에 따른 차이를 비교할 수 있습니다.','Distinguish basic-instruction results on eight Meta-World tasks from detailed-instruction results reported for four tasks. Each task is evaluated over 50 trials; the explorer compares how instruction detail affects performance.'),
'caption':B('그림 1. 언어 조건 기반 3D 표현 학습 구조','Figure 1. Language-conditioned 3D representation learning architecture.'),
'metric_refs':['Table 1 (Meta-World)','Table 1 (Mean success rate)','Table 1 (Basic instructions)']}
D['act-cbam']={
'problem':[
block('추가 시연 없이 남아 있는 제어 오류를 줄이기','Reduce control errors without more demonstrations','ACT는 시연으로 visual encoder를 fine-tuning한 뒤에도 정밀한 insertion 과업에서 낮은 성공률을 보였습니다. 데이터를 더 모으기보다, 이미 주어진 영상에서 제어에 중요한 정보를 충분히 활용하는지에 주목했습니다.','ACT still has limited success on precise insertion after fine-tuning its visual encoder on demonstrations. Rather than collecting more data, the study asks whether the policy is making effective use of control-relevant information already present in its visual input.','§1'),
block('무엇과 어디에 집중할지 분리','Separate what to attend to from where','모든 channel과 spatial location이 행동 예측에 똑같이 유용하지는 않습니다. Channel attention과 spatial attention을 결합해 필요한 feature를 강조하면서, adapter 방식으로 학습 가능한 파라미터 수를 줄이는 방향을 택했습니다.','Not every channel or spatial location is equally useful for action prediction. The design combines channel and spatial attention to emphasize relevant features, using an adapter to reduce the number of trainable parameters.','§1–2'),
block('Attention을 추가했다는 사실보다 효과를 검증','Test the components rather than assume attention helps','Channel-only, spatial-only, 두 attention의 결합을 각각 비교했습니다. Channel-only는 두 과업 모두 baseline보다 낮았고, 순차적으로 결합한 CBAM이 가장 높은 성공률을 보였습니다. 이 비교를 통해 단순한 모듈 추가와 실제 제어 성능 개선을 구분했습니다.','Compare channel-only, spatial-only, and combined attention. Channel-only performs below the baseline on both tasks, whereas sequential CBAM achieves the highest success rates. This ablation distinguishes adding a module from actually improving control.','Table 1')],
'method':[
block('Channel attention 다음 spatial attention','Channel attention followed by spatial attention','CBAM은 visual feature map에 channel attention을 먼저 적용한 후, 갱신된 feature에 spatial attention을 적용합니다. 중요한 feature와 위치를 순차적으로 강조합니다.','CBAM first applies channel attention to the visual feature map, then applies spatial attention to the updated features. This sequentially emphasizes relevant features and locations.','§2 · Equations 1–3'),
block('동결된 visual encoder와 학습 가능한 adapter','A frozen visual encoder with a trainable adapter','ResNet18 visual encoder는 동결하고 CBAM을 adapter로 학습합니다. 다른 policy component의 학습은 유지하면서, 과업별 50개 시연으로 학습한 모델의 성공률과 전체 trainable parameter 수를 함께 비교합니다.','Freeze the ResNet18 visual encoder and train CBAM as an adapter while continuing to train the other policy components. With 50 demonstrations per task, compare both task success and the total number of trainable parameters.','§2–3 · Table 1')],
'results_intro':B('Transfer Cube와 Insertion에서 세 attention 구성을 baseline ACT와 비교합니다. 성공률은 3개 학습 seed에서 각 50회 평가한 평균이고, parameter 수는 학습 가능한 파라미터를 뜻합니다.','Compare three attention configurations with baseline ACT on Transfer Cube and Insertion. Success rates average 50 evaluations for each of three training seeds; parameter counts refer to trainable parameters.'),
'caption':B('그림 1. 전체 구조도','Figure 1. Overall architecture.'),
'metric_refs':['Table 1 (Transfer Cube)','Table 1 (Insertion)','Table 1 (Trainable parameters)']}
