"""저자 제공 논문에서 확인한 한·영 연구 설명과 표 데이터. 수치는 두 언어가 공유합니다."""
def B(ko,en): return {'ko':ko,'en':en}
def study(title,cols,rows,source,unit='%',maximum=100,digits=1):
 return dict(title=title,cols=cols,rows=rows,source=source,unit=unit,maximum=maximum,digits=digits)
def step(ko,en,kdesc,edesc): return [B(ko,en),B(kdesc,edesc)]
PAPERS=[
 dict(slug='endcache',name='EndCache',venue=B('Mathematics · 2026','Mathematics · 2026'),category='efficiency',kind='cache',
 title=B('생성형 로봇 정책에서 무엇을 재사용해야 할까?','What to Reuse in Generative Robot Policies?'),
 subtitle=B('행동 생성을 위한 학습 없는 출력 캐싱의 솔버 관점 수학적 분석','A Solver-Aware Mathematical Analysis of Training-Free Output Caching for Action Generation'),
 authors=['Jiwon Kim¹','Jaekwon Lee¹˒²','Jaekoo Lee¹†'],affiliation=B('¹ 국민대학교 · ² 한성대학교','¹ Kookmin University · ² Hansung University'),authornote=B('† 교신저자','† Corresponding author'),
 tags=['VLA','Diffusion','Flow Matching','Training-free'],
 lead=B('호출을 줄이기 전에, 안정적으로 재사용할 수 있는 출력부터 찾습니다.','Before skipping a call, choose a stable quantity to reuse.'),
 abstract=B('같은 횟수로 모델을 호출해도 무엇을 저장하느냐에 따라 로봇의 성공률은 크게 달라집니다. EndCache는 수치 솔버에 따라 출력 재사용의 의미를 구분하고, 확률적 확산 모델에서는 잡음 대신 깨끗한 행동의 추정값인 endpoint를 재사용합니다. 정책을 다시 학습하지 않고 호출 수와 추론 지연을 줄이는 방법을 수학적 분석과 폐루프 평가로 검증했습니다.','The same evaluation budget can produce very different robot success rates depending on what is cached. EndCache distinguishes reuse by numerical solver and, for stochastic diffusion, reuses the estimated clean-action endpoint rather than raw noise. Mathematical analysis and closed-loop evaluation examine how output caching reduces calls and inference latency without retraining the policy.'),
 metrics=[['73.7 pp',B('Endpoint–noise 성공률 차이','Endpoint–noise success gap')],['2.71×',B('π0.5 전체 모델 추론 가속','π0.5 model-inference speedup')],['10 → 1',B('π0.5 호출 수 · k=10','π0.5 calls · k=10')]],
 metricnote=B('원문 표 3·5·11. 73.7 pp는 Diffusion Policy의 출력 공간 비교입니다. 호출 수 감소와 실제 지연 가속은 서로 다른 지표입니다.','Tables 3, 5 and 11. The 73.7 pp gap compares output spaces in Diffusion Policy. Call-count reduction and measured latency speedup are distinct metrics.'),
 sections=[
 [B('반복 호출보다 먼저 살펴볼 재사용 공간','Ask what to reuse—not only when'),B('하나의 행동 청크를 생성하는 동안 행동 생성기가 반복 호출됩니다. 인접 출력의 유사성만으로는 캐싱의 안정성을 보장할 수 없습니다. 잡음, 속도, endpoint가 솔버 내부에서 각각 어떻게 작용하는지 구분해야 합니다.','An action generator is evaluated repeatedly within one action chunk. Similar adjacent outputs alone do not establish safe caching: noise, velocity and endpoints enter numerical solvers differently.')],
 [B('결정론적 흐름 매칭과 확률적 확산을 구분','Separate deterministic FM from stochastic diffusion'),B('결정론적 선형 흐름 매칭의 Euler 적분에서 블록 단위 속도 재사용은 성긴 격자 Euler 적분과 등가입니다. 균일 격자에서 k가 N을 나누면 기본 N/k 단계 추론과 같습니다. 반면 매 단계 새 잡음을 주입하는 ancestral sampler에서는 이 등가성이 깨지므로 재사용 공간이 중요합니다.','For deterministic linear-FM Euler integration, blockwise velocity reuse is equivalent to coarse-grid Euler. On a uniform grid with k dividing N, it is native N/k-step inference. This equivalence fails in ancestral samplers that inject fresh noise at each fine step, making the reuse space consequential.')],
 [B('잡음 오차와 endpoint 오차의 전달 방식','How stale noise becomes endpoint error'),B('캐싱된 잡음 예측의 오차는 endpoint로 변환할 때 σ/α = SNR⁻¹ᐟ²만큼 증폭됩니다. Endpoint를 직접 재사용하면 원문 가정하에서 오차가 비팽창적으로 전달됩니다. 관측 조건부 사후 공분산과 endpoint Jacobian의 관계를 분석하되, 국소 민감도 분석을 모든 과업의 성공 보장으로 해석하지 않습니다.','A stale noise prediction is amplified by σ/α = SNR⁻¹ᐟ² when converted to an endpoint. Direct endpoint reuse propagates staleness non-expansively under the stated assumptions. The analysis connects conditional posterior covariance to the endpoint Jacobian, without claiming a universal task-success guarantee.')]],
 steps=[step('관측 고정','Condition','하나의 행동 청크 안에서 관측 조건을 고정합니다. 제어 주기 사이에서 실행 행동을 고정하는 방법은 아닙니다.','Keep conditioning fixed within one action chunk; this does not hold executed actions across control cycles.'),step('출력 선택','Select output','FM은 속도, ε 예측 확산은 변환된 endpoint, x₀ 예측 확산은 직접 endpoint를 저장합니다.','Cache FM velocity, reconstructed endpoints for ε prediction, or direct endpoints for x₀ prediction.'),step('주기적 갱신','Refresh','i mod k = 0에서만 행동 생성기를 호출하고, 나머지 단계에서도 기본 솔버 상태 갱신은 수행합니다.','Evaluate the generator when i mod k = 0; native solver updates still run at intermediate steps.'),step('폐루프 평가','Evaluate','호출 수·전체 모델 지연·과업 성공률을 별도로 측정합니다.','Measure calls, model-inference latency and task success separately.')],
 intro=B('모델과 재사용 간격을 선택해 실제 보고된 지연·성공률과 계산된 호출 위치를 함께 살펴보세요.','Select a model and reuse interval to inspect reported latency and success alongside the calculated call schedule.'),
 studies=[study(B('같은 예산, 다른 재사용 공간','Same budget, different reuse spaces'),['Success'],[['Baseline · k=1',87.2],['Endpoint hold · k=10',85.9],['Endpoint extrapolate',81.9],['Noise hold · k=10',12.2],['Noise extrapolate',3.7]],B('원문 표 3 · 약 60개 Diffusion Policy 체크포인트','Table 3 · approximately 60 Diffusion Policy checkpoints'))],
 limits=B('폐루프 검증은 시뮬레이션입니다. 전체 추론 지연(E2E)은 VLM과 행동 생성기만 포함하며 카메라 획득·통신·제어기 실행까지 포함한 전체 관측–행동 루프가 아닙니다. FM 결과는 새로운 솔버의 우월성보다 등가성과 계산 예산을 검증하는 결과로 읽어야 합니다.','Closed-loop validation is in simulation. E2E latency includes the VLM and action generator, not the complete camera–communication–controller loop. FM results verify numerical equivalence and computation budgets, not superiority of a new solver.'),
 source=B('저자 제공 mathematics-4529257.pdf · 24쪽 · 그림 2, 표 3·5·6·11','Author-provided mathematics-4529257.pdf · 24 pages · Figure 2, Tables 3, 5, 6 and 11'),
 figure=B('원문 그림 2. π0.5, k=5에서의 호출 스케줄과 행동 생성기(AG) 지연. 상단 2.71× 수치는 k=10의 전체 모델 추론 결과입니다.','Original Figure 2. Call schedule and action-generator (AG) latency for π0.5 at k=5. The headline 2.71× is whole-model inference at k=10.'),
 code='https://github.com/KJW988/EndCache',bibauthors='Kim, Jiwon and Lee, Jaekwon and Lee, Jaekoo',bibvenue='Mathematics',year=2026),
 dict(slug='velocity-reuse',name='Velocity Reuse',venue=B('IEIE · 2026','IEIE · 2026'),category='efficiency',kind='cache',
 title=B('속도 재사용을 통한 흐름 매칭 기반 VLA 추론 가속','Training-Free Inference Acceleration for Flow-Matching-Based Vision-Language-Action Models via Velocity Reuse'),
 subtitle=B('추가 학습 없이 생성 단계 사이의 중복성을 활용합니다.','Reusing stable velocity outputs across generation steps—without retraining.'),
 authors=['Jiwon Kim','Taejin Park','Jaekwon Lee','Jaekoo Lee†'],affiliation=B('국민대학교 컴퓨터공학과','Kookmin University'),authornote=B('† 교신저자','† Corresponding author'),tags=['VLA','Flow Matching','LIBERO'],
 lead=B('이미 계산한 속도를 다음 생성 단계에서도 쓸 수 있을까?','Can the next generation step reuse the velocity we already computed?'),
 abstract=B('흐름 매칭 VLA에서 인접 생성 단계의 속도 방향과 크기가 매우 유사하다는 관찰에서 출발했습니다. 일정 간격으로만 속도를 다시 계산하고 중간 단계에서 재사용하여, 정책의 추가 학습 없이 행동 생성 지연을 줄입니다. π0.5와 GR00T-N1.7을 대상으로 성공률과 지연을 구분해 평가했습니다.','We start from the observation that adjacent flow-matching outputs have highly similar directions and magnitudes. Recomputing velocity at fixed intervals and reusing it between refreshes reduces action-generation latency without retraining. Experiments on π0.5 and GR00T-N1.7 evaluate success and latency separately.'),
 metrics=[['14.91×',B('π0.5 행동 전문가 가속','π0.5 action-expert speedup')],['2.79×',B('π0.5 전체 모델 추론 가속','π0.5 whole-model speedup')],['±0.5 pp',B('π0.5 평균 성공률 변동 범위','π0.5 mean success variation')]],
 metricnote=B('IEIE 원문 표 2–4. 최대 가속은 π0.5의 k=10 측정값입니다. 별도 EndCache 원고의 프로파일링 수치와 혼합하지 않습니다.','IEIE Tables 2–4. Maximum speedups are for π0.5 at k=10. These timings are distinct from those in the EndCache manuscript.'),
 sections=[
 [B('관찰: 단계 사이의 안정적인 속도','Observe stable velocities'),B('LIBERO 네 환경에서 π0.5의 인접 단계 코사인 유사도 평균은 0.9997, 노름 비율은 0.9984였습니다. GR00T-N1.7의 인접 코사인 유사도도 평균 0.9963으로 높았습니다. 이는 평가한 모델·조건의 경험적 관찰입니다.','Across four LIBERO suites, π0.5 has mean adjacent cosine similarity 0.9997 and norm ratio 0.9984. GR00T-N1.7 also has high adjacent cosine similarity, averaging 0.9963. These are observations on the tested models and conditions.')],
 [B('방법: 새 계산과 재사용을 분리','Separate fresh calls from reused updates'),B('첫 단계에서 속도를 계산한 뒤 k개 단계마다 갱신합니다. 중간에는 가장 최근에 계산한 속도로 Euler 상태를 갱신합니다. N=10, k=5라면 모델 호출은 10회에서 2회로 줄지만 솔버의 중간 상태 갱신은 계속됩니다.','Evaluate velocity initially and refresh every k steps. Between refreshes, apply Euler updates using the held velocity. N=10 and k=5 reduce calls from ten to two, while intermediate solver-state updates remain.')],
 [B('검증: 잡음 조건을 구분','Distinguish noise protocols'),B('Paired는 비교 대상의 환경 초기화와 초기 행동 잡음을 고정하고, Random은 제어 단계마다 초기 잡음을 추출합니다. 3개 시드에서 성공률을 평가하고 A6000에서 워밍업 30회·반복 100회로 지연을 측정했습니다.','Paired fixes resets and initial action noise for comparisons; Random samples new initial action noise each control step. Success is evaluated across three seeds, with latency profiled on an A6000 using 30 warmups and 100 repetitions.')]],
 steps=[step('관측 입력','Condition','이미지·언어 지시·로봇 상태를 사용해 행동 생성을 조건화합니다.','Condition generation on images, language and robot state.'),step('새 속도 계산','Fresh velocity','첫 단계와 정해진 갱신 단계에서 행동 생성기를 호출합니다.','Evaluate the action generator initially and at scheduled refreshes.'),step('속도 재사용','Velocity hold','중간 단계에서는 저장된 속도로 상태를 갱신합니다.','Use the held velocity for intermediate state updates.'),step('행동 청크 출력','Action chunk','최종 행동 청크를 기존 실행 구조로 전달합니다.','Pass the final action chunk to the original execution stack.')],
 intro=B('Paired·Random 조건을 구분해 비교하세요. 슬라이더는 원문에 보고된 간격만 선택합니다.','Compare Paired and Random protocols. The slider selects only intervals reported in the paper.'),
 studies=[study(B('단계 간 속도 안정성','Inter-step velocity stability'),['Adjacent cosine','Far cosine','Adjacent norm ratio','Far norm ratio'],[['π0.5',.9997,.9945,.9984,.9859],['GR00T-N1.7',.9963,.9774,.9971,.9914]],B('원문 표 1 · LIBERO 4개 환경 평균','Table 1 · mean across four LIBERO suites'),'',1,4)],
 limits=B('속도의 안정성이 모든 흐름 매칭 정책에서 보장되는 것은 아닙니다. 이 학회 원고는 출력 재사용의 경험적 효과에 초점을 둡니다. 별도 EndCache 원고에서는 결정론적 Euler 조건에서의 성긴 격자 적분과의 등가성을 분석합니다. 두 원고의 실험 수치와 논지를 구분해야 합니다.','Velocity stability is not guaranteed for every flow-matching policy. This conference manuscript focuses on empirical output reuse; the separate EndCache manuscript analyzes coarse-grid equivalence under deterministic Euler. Keep their measurements and framing distinct.'),
 source=B('저자 제공 IEIE2026_김지원.pdf · 5쪽 · 그림 1, 표 1–4','Author-provided IEIE2026_김지원.pdf · 5 pages · Figure 1, Tables 1–4'),
 figure=B('원문 그림 1. 재사용 스케줄 설명. 지연·가속의 정확한 비교는 아래 표 4 기반 탐색기를 따릅니다.','Original Figure 1. Reuse schedule illustration. Use the Table-4 explorer below for the latency and speedup comparison.'),
 bibauthors='Kim, Jiwon and Park, Taejin and Lee, Jaekwon and Lee, Jaekoo',bibvenue='IEIE',year=2026),
 dict(slug='star',name='STAR',
 venue=B('AUTOPILOT Workshop @ CVPR 2026 · Non-archival','AUTOPILOT Workshop @ CVPR 2026 · Non-archival'),
 category='perception',kind='study',
 title=B('STAR: Stage-wise Traffic Accident Detection via Optical-Flow-Guided Reasoning',
         'STAR: Stage-wise Traffic Accident Detection via Optical-Flow-Guided Reasoning'),
 subtitle=B('',''),
 authors=['Jaesung Sung*','Jiwon Kim*','Rian Ryu','Minseok Lim','Geonung Choi','Minju Jeong','Jaekoo Lee†'],
 affiliation=B('국민대학교 컴퓨터공학과','Kookmin University'),
 authornote=B('* 공동 제1저자 · 동등 기여　† 교신저자',
              '* Equal contribution　† Corresponding author'),
 tags=['VLM','Video Understanding','Non-archival'],
 lead=B('CVPR 2026 AUTOPILOT Workshop Non-archival 발표',
        'Non-archival presentation at AUTOPILOT Workshop @ CVPR 2026'),
 abstract=B('본 연구는 AUTOPILOT Workshop @ CVPR 2026의 Non-archival 트랙에 발표되었습니다.',
            'Presented at the Non-archival Track of AUTOPILOT Workshop @ CVPR 2026.'),
 metrics=[],metricnote=B('',''),sections=[],steps=[],intro=B('',''),studies=[],
 limits=B('',''),source=B('',''),figure=B('',''),code=None,
 bibauthors='Sung, Jaesung and Kim, Jiwon and Ryu, Rian and Lim, Minseok and Choi, Geonung and Jeong, Minju and Lee, Jaekoo',
 bibvenue='AUTOPILOT Workshop @ CVPR 2026',year=2026),
 dict(slug='navila-patch',name='VLN Patch Study',venue=B('IPIU · 2026','IPIU · 2026'),category='robustness',kind='study',
 title=B('자연어 행동 기반 시각–언어 내비게이션의 적대적 패치 취약성','Adversarial Patch Attacks on Vision-Language Navigation with Natural Language Action'),subtitle=B('패치의 생성 방식·크기·노출 구간이 주행 품질에 미치는 영향','How patch construction, size and exposure affect navigation quality'),
 authors=['Jiwon Kim','Taejin Park','Jaekoo Lee†'],affiliation=B('국민대학교 컴퓨터공학과','Kookmin University'),authornote=B('† 교신저자','† Corresponding author'),tags=['VLN','NaVILA','Robustness'],lead=B('작은 시각 교란이 전체 경로에 영향을 미칠 수 있습니다.','A localized visual disturbance can affect the entire route.'),
 abstract=B('NaVILA의 모델 가중치를 고정하고 입력 패치만 학습해 자연어 행동 기반 내비게이션의 강건성을 평가했습니다. 가림·잡음·학습된 패치를 비교하고 크기와 노출 조건을 분리해, 성공률과 경로 효율이 어떤 조건에서 달라지는지 분석합니다.','We evaluate NaVILA’s robustness by learning an input patch while keeping policy weights fixed. Comparing occlusion, untrained noise and learned patches—and separating size from exposure—reveals changes in navigation success and path efficiency.'),
 metrics=[['54.0 → 38.6%',B('R2R-CE 성공률','R2R-CE success')],['52.1 → 39.8%',B('RxR-CE 성공률','RxR-CE success')],['57 / 384 px',B('패치 한 변 / 입력 한 변','Patch side / input side')]],metricnote=B('원문 표 1 · 모든 관찰에 노출되는 Ideal 조건. 15%는 대략적인 한 변 비율이며 면적의 15%가 아닙니다.','Table 1 · Ideal exposure on all observations. “15%” approximates a side-length ratio, not 15% of image area.'),
 sections=[
 [B('시각 교란에서 실제 주행 품질까지','From visual disturbance to navigation quality'),B('교란된 입력은 시각–언어 추론, 자연어 행동 생성, 명령 파싱을 거쳐 주행 실패로 이어질 수 있습니다. 분류 결과만이 아니라 목표 도달과 경로 효율을 평가합니다.','Perturbed inputs pass through visual-language reasoning, natural-language action generation and command parsing. Evaluation measures goal reaching and path efficiency, not just a changed image prediction.')],
 [B('모델은 고정하고 패치만 학습','Optimize the patch, not the policy'),B('현재 관찰 1장과 과거 7장에 패치를 적용합니다. 회전·전단 변환으로 시점 변화를 모사하고, 자연어 행동 포맷을 유지하면서 잘못된 목표 행동을 유도하도록 학습합니다.','Apply the patch to one current and seven historical observations. Rotation and shear approximate viewpoint changes. Optimization targets incorrect actions while retaining the natural-language action format.')],
 [B('가림 효과와 학습 효과를 분리','Separate occlusion and learned effects'),B('검정 패치와 가우시안 초기화 패치를 비교 대상으로 두고 R2R-CE·RxR-CE Val-Unseen에서 NE·OS·SR·SPL을 측정합니다. 크기 실험과 노출 주기 실험은 별도 조건으로 보고합니다.','Use black and Gaussian-initialized patches as controls on R2R-CE and RxR-CE Val-Unseen. NE, OS, SR and SPL capture distance, success and route efficiency. Size and exposure are separate studies.')]],
 steps=[step('관찰 입력','Observations','과거 7장, 현재 1장과 자연어 지시를 입력합니다.','Use seven past and one current observation with an instruction.'),step('패치 조건','Patch condition','가림·잡음·학습된 패치의 영향을 구분합니다.','Separate occlusion, noise and learned-patch effects.'),step('행동 생성','Actions','고정된 NaVILA의 자연어 출력을 시뮬레이터 명령으로 변환합니다.','Convert frozen NaVILA outputs into simulator commands.'),step('주행 평가','Evaluation','Val-Unseen의 도달 오차·성공률·경로 품질을 비교합니다.','Compare distance error, success and route quality on Val-Unseen.')],
 intro=B('데이터셋·비교 실험·지표를 선택하세요. 측정하지 않은 크기·노출 조합의 결과는 만들지 않습니다.','Select a dataset/study and metric. Unmeasured size–exposure combinations are not fabricated.'),studies=[],
 limits=B('평가는 VLN-CE 시뮬레이션입니다. 기하학적 변환으로 시점 변화를 모사했지만 실제 로봇에 패치를 부착한 실험을 뜻하지는 않습니다. 54.0% → 38.6%는 −15.4 pp이며 상대 하락률은 약 28.5%입니다. 서로 다른 비율을 혼동하지 않습니다.','Evaluation is in VLN-CE simulation. Geometric augmentation approximates viewpoint changes, but this is not a physical patch experiment on a real robot. A drop from 54.0% to 38.6% is −15.4 pp, or about 28.5% relative—not the same measure.'),source=B('저자 제공 IPIU 2026 원고 · 6쪽 · 그림 1, 표 1–3','Author-provided IPIU 2026 manuscript · 6 pages · Figure 1, Tables 1–3'),figure=B('원문 그림 1. 패치 학습 및 적용 구조. 결과 탐색기는 기존 실험값만 보여주며 공격을 실행하지 않습니다.','Original Figure 1. Patch learning and application. The explorer shows reported values only; it does not run attacks.'),bibauthors='Kim, Jiwon and Park, Taejin and Lee, Jaekoo',bibvenue='IPIU',year=2026),
 dict(slug='lift3d-film',name='Lift3D + FiLM',venue=B('ISET · 2025 · 우수논문상','ISET · 2025 · Best Paper Award'),category='control',kind='film',
 title=B('언어 조건 기반 3D 표현 학습을 통한 로봇 제어 성능 향상','Enhancing Robot Control through Language-Conditioned 3D Representation Learning'),subtitle=B('공간 표현에 과업의 목표를 더합니다.','Bringing task intent into spatial representations.'),
 authors=['Jiwon Kim','Sungsik Kim','Jaekoo Lee†'],affiliation=B('국민대학교 컴퓨터공학과','Kookmin University'),authornote=B('† 교신저자','† Corresponding author'),tags=['3D Policy','FiLM','Meta-World'],lead=B('어디에 있는지를 넘어, 무엇을 해야 하는지 반영합니다.','Represent not only where things are, but what the task requires.'),
 abstract=B('Lift3D의 3D 표현 학습에 언어 조건을 결합합니다. CLIP 텍스트 임베딩에서 생성한 FiLM 매개변수로 시각 특징을 조정해 같은 공간 관찰에도 과업의 목표가 반영되도록 설계했습니다. 지시문을 상세하게 작성했을 때의 효과도 별도로 평가했습니다.','We add language conditioning to Lift3D’s 3D representation learning. FiLM parameters generated from CLIP text embeddings modulate visual features so task intent can shape the representation. A separate study evaluates more detailed instructions.'),
 metrics=[['71.0 → 76.3%',B('8개 과업 평균 · 기본 지시문','8-task mean · basic instruction')],['+5.3 pp',B('평균 성공률 차이','Mean success difference')],['7 / 8',B('기본 지시문에서 개선된 과업','Tasks improved with basic text')]],metricnote=B('원문 표 1의 반올림된 평균 기준. sweep into는 기본 조건에서 74% → 72%로 하락했습니다.','Rounded means from Table 1. Sweep-into success decreases from 74% to 72% with basic instructions.'),
 sections=[
 [B('공간 구조만으로 결정되지 않는 목표','Geometry alone does not specify intent'),B('RGBD에서 얻은 포인트 클라우드는 공간 구조를 담지만 무엇과 어떤 상호작용을 할지는 과업에 달려 있습니다. Lift3D의 두 번째 학습 단계에 언어 정보를 더해 이러한 목표를 표현에 반영합니다.','RGBD-derived point clouds capture geometry, but the intended interaction depends on the task. Language is added to Lift3D’s second training stage to condition the representation on that intent.')],
 [B('언어가 시각 특징을 스케일·시프트','Language scales and shifts visual features'),B('CLIP 텍스트 임베딩을 MLP 기반 FiLM 생성기에 입력해 γ·β를 얻고 H′ = γ ⊙ H + β를 적용합니다. CLIP-ViT의 매 세 번째 블록에서 특징을 조정하며 LoRA 기반 미세조정을 사용합니다.','An MLP FiLM generator maps CLIP text embeddings to γ and β and applies H′ = γ ⊙ H + β. Features are modulated at every third CLIP-ViT block, alongside LoRA fine-tuning.')],
 [B('지시문의 구체성이 만드는 차이','Instruction specificity matters'),B('기본 설명에서는 8개 중 7개 과업이 개선되었습니다. sweep into의 하락을 확인한 뒤 객체와 동작을 명확히 한 상세 지시문으로 4개 과업을 추가 평가했습니다. 상세 조건의 8개 전체 평균은 보고되지 않았습니다.','Basic descriptions improve seven of eight tasks. After observing a sweep-into regression, four tasks are additionally evaluated with explicit object-and-action instructions. No eight-task detailed-instruction mean is reported.')]],
 steps=[step('3D 관찰','3D observation','포인트 클라우드를 토큰화하고 위치 임베딩을 결합합니다.','Tokenize point clouds and combine positional embeddings.'),step('언어 조건','Language','텍스트 임베딩으로부터 FiLM 매개변수 γ·β를 만듭니다.','Generate FiLM parameters γ and β from text embeddings.'),step('특징 조정','Modulation','과업 목표에 따라 시각 은닉 상태를 스케일·시프트합니다.','Scale and shift visual hidden states according to task intent.'),step('행동 예측','Action','조정된 특징과 로봇 상태로 위치 변화와 gripper를 예측합니다.','Predict position changes and gripper from features and robot state.')],
 intro=B('과업을 선택해 기준 모델·기본 지시문·상세 지시문을 비교하세요. 미보고된 상세 조건은 비워 둡니다.','Select a task to compare baseline, basic and detailed instructions. Unreported detailed conditions are left missing.'),
 studies=[study(B('과업별 성공률','Per-task success'),[B('Lift3D','Lift3D'),B('기본 지시문','Basic'),B('상세 지시문','Detailed')],[['assembly',94,98,None],['bin picking',82,94,None],['box close',94,96,None],['hammer',76,84,None],['hand insert',68,70,76],['push wall',34,42,44],['shelf place',46,54,58],['sweep into',74,72,82]],B('원문 표 1–2 · Meta-World · 과업당 50회 평가','Tables 1–2 · Meta-World · 50 evaluations/task'))],
 limits=B('Meta-World 시뮬레이션에서 객체 위치를 무작위화해 평가했습니다. 상세 지시문 결과는 4개 과업에만 있습니다. 아래 FiLM 예시는 수식 이해를 돕는 가상 특징값이지 학습된 모델의 실제 활성값이 아닙니다.','Evaluation uses randomized object positions in Meta-World simulation. Detailed-instruction results cover only four tasks. The FiLM arithmetic illustration uses hypothetical features, not learned model activations.'),source=B('저자 제공 ISET 2025 원고 · 3쪽 · 그림 1, 표 1–2. 수상 정보는 저자 CV 기준.','Author-provided ISET 2025 manuscript · 3 pages · Figure 1, Tables 1–2. Award metadata follows the author CV.'),figure=B('원문 그림 1. CLIP 기반 3D 표현 학습에 언어 조건을 통합하는 구조.','Original Figure 1. Integrating language conditioning into CLIP-based 3D representation learning.'),bibauthors='Kim, Jiwon and Kim, Sungsik and Lee, Jaekoo',bibvenue='IEMEK Symposium on Embedded Technology (ISET)',year=2025),
 dict(slug='act-cbam',name='ACT + CBAM',venue=B('KAIC · 2024','KAIC · 2024'),category='control',kind='study',
 title=B('개선된 시각적 어텐션 어댑터를 통한 로봇 제어 성능 향상','Enhancing Robot Control with Advanced Visual Attention Adapter'),subtitle=B('같은 시연 데이터에서 중요한 시각 정보를 더 잘 활용합니다.','Use the same demonstrations—and attend to the visual information that matters.'),
 authors=['Jiwon Kim','Minsung Kim','Taejin Park','Jaekoo Lee†'],affiliation=B('국민대학교 컴퓨터공학과','Kookmin University'),authornote=B('† 교신저자','† Corresponding author'),tags=['ACT','CBAM','Imitation Learning'],lead=B('시연을 더 모으기 전에, 무엇을 보고 있는지 개선합니다.','Before collecting more demonstrations, improve what the policy attends to.'),
 abstract=B('ACT의 시각 인코더에 채널·공간 어텐션을 결합한 CBAM 어댑터를 추가했습니다. 사전 학습된 ResNet18을 동결하고 어댑터를 학습하여 추가 시연 없이, 적은 학습 가능 매개변수로 두 시뮬레이션 과업의 성공률을 높였습니다.','We add a CBAM adapter combining channel and spatial attention to ACT’s visual encoder. Freezing pretrained ResNet18 and training the adapter improves two simulation tasks with fewer trainable parameters and no additional expert demonstrations.'),
 metrics=[['93 → 96%',B('큐브 전달 성공률','Transfer Cube success')],['55 → 61%',B('삽입 성공률','Insertion success')],['−11.13 M',B('학습 가능 매개변수 차이','Trainable parameter difference')]],metricnote=B('원문 표 1. 11.13M은 83.92M − 72.79M으로 계산했습니다. 전체 모델 크기가 아닌 학습 가능한 매개변수의 비교입니다.','Table 1. 11.13M is derived from 83.92M − 72.79M. This compares trainable parameters, not total model size.'),
 sections=[
 [B('모든 시각 정보가 똑같이 중요하지는 않습니다','Not every visual feature matters equally'),B('정밀 삽입은 객체의 위치와 관계를 세밀하게 파악해야 합니다. 중요한 특징과 위치를 강조해 같은 시연에서 더 유용한 제어 표현을 학습하고자 했습니다.','Precise insertion requires understanding object locations and relations. Emphasizing relevant features and positions aims to learn more useful control representations from the same demonstrations.')],
 [B('무엇을 본 뒤, 어디를 볼지 조정','Attend to what, then where'),B('채널 어텐션을 적용한 뒤 공간 어텐션을 순차 적용합니다. 기존 ACT처럼 ResNet18 전체를 미세조정하는 대신 시각 인코더를 동결하고 CBAM을 어댑터로 학습합니다. 정책의 다른 부분까지 전부 동결했다는 뜻은 아닙니다.','Apply channel attention followed by spatial attention. Instead of fully fine-tuning ResNet18 as in ACT, freeze the visual backbone and train CBAM as an adapter. This does not imply freezing every other policy component.')],
 [B('구성요소를 분리해 효과 검증','Disentangle the components'),B('ACT, 채널만 적용, 공간만 적용, 순차 결합을 비교합니다. 과업별 50개 시연으로 학습하고 3개 학습 시드에서 각 50회 평가한 평균 성공률을 보고합니다.','Compare ACT, channel-only, spatial-only and sequential attention. Train on 50 demonstrations per task and report mean success across three training seeds with 50 evaluations each.')]],
 steps=[step('관찰 이미지','Images','추가 수집 없이 같은 시연과 관찰을 사용합니다.','Use the same demonstrations and observations.'),step('동결된 인코더','Frozen encoder','사전 학습 ResNet18의 가중치를 고정합니다.','Freeze pretrained ResNet18 weights.'),step('채널 → 공간','Channel → spatial','CBAM이 특징과 위치를 순차적으로 조정합니다.','CBAM sequentially modulates channels and locations.'),step('행동 청크','Action chunk','조정된 특징을 ACT 행동 시퀀스 생성에 사용합니다.','Use modulated features for ACT action-sequence generation.')],
 intro=B('성공률과 학습 가능한 매개변수를 지표별로 살펴보세요. 채널·공간 각각의 결과도 함께 비교합니다.','Inspect success and trainable parameters, including channel-only and spatial-only ablations.'),
 studies=[study(B('성공률','Task success'),[B('큐브 전달','Transfer Cube'),B('삽입','Insertion')],[['ACT',93,55],['ACT + Channel',84,52],['ACT + Spatial',91,60],['ACT + CBAM',96,61]],B('원문 표 1 · 3개 학습 시드 × 각 50회 평가','Table 1 · 3 training seeds × 50 evaluations each')),study(B('학습 가능 매개변수','Trainable parameters'),[B('매개변수','Parameters')],[['ACT',83.92],['ACT + Channel',72.79],['ACT + Spatial',72.79],['ACT + CBAM',72.79]],B('원문 표 1 · 전체 모델 크기가 아닌 학습 가능 매개변수','Table 1 · trainable parameters, not total model size'),' M',100,2)],
 limits=B('두 과업의 시뮬레이션 결과를 모든 실제 환경으로 일반화할 수는 없습니다. 채널만 사용하면 두 과업 모두 기준 ACT보다 낮고, 공간만 사용하면 큐브 전달이 낮았습니다. 실제 환경과 더 다양한 정책에서의 검증은 후속 과제로 남습니다.','Results on two simulated tasks do not establish improvement in all real environments. Channel-only attention underperforms ACT on both tasks, and spatial-only regresses on Transfer Cube. Real-world and broader policy validation remain future work.'),source=B('저자 제공 KAIC 2024 원고 · 2쪽 · 그림 1, 표 1','Author-provided KAIC 2024 manuscript · 2 pages · Figure 1, Table 1'),figure=B('원문 그림 1. ACT 인코더·디코더와 동결된 시각 인코더에 추가한 CBAM 어댑터.','Original Figure 1. ACT encoder/decoder and the CBAM adapter attached to the frozen visual encoder.'),bibauthors='Kim, Jiwon and Kim, Minsung and Park, Taejin and Lee, Jaekoo',bibvenue='KAIC',year=2024)
]
# 행 순서: k, 성공률 평균, 성공률 표준편차, AG ms, E2E ms, AG 배속, E2E 배속.
PAPERS[0]['cache']=[
 dict(name='π0.5 · LIBERO',N=10,source=B('원문 표 5·11','Tables 5, 11'),rows=[[1,96.8,.3,221.3,324.4,1,1],[2,97.3,.2,106.5,209.6,2.08,1.55],[3,96.8,.4,85.7,188.8,2.58,1.72],[4,97,.3,60.2,163.3,3.67,1.99],[5,97,.3,37.6,140.7,5.89,2.31],[10,96.8,.1,16.4,119.5,13.50,2.71]]),
 dict(name='GR00T-N1.7 · LIBERO',N=4,source=B('원문 표 5·11','Tables 5, 11'),rows=[[1,97.1,.3,101.1,148,1,1],[2,97.3,.7,47.4,89.7,2.13,1.65],[4,96.2,.7,25.2,67.4,4.01,2.19]]),
 dict(name='RDT-1B · ManiSkill',N=5,source=B('원문 표 6·11','Tables 6, 11'),rows=[[1,50.6,1.1,145.2,300.2,1,1],[2,49.8,1.6,94.9,250,1.53,1.20],[3,51.5,2.1,58.2,213.3,2.49,1.41],[5,49.2,1.9,37.7,192.8,3.85,1.56]])]
paired=[[1,96.7,None,227.4,330.5,1,1],[2,96.8,None,108.6,211.7,2.09,1.56],[3,96.8,None,85.3,188.4,2.67,1.75],[4,96.7,None,60.8,164,3.74,2.02],[5,96.9,None,38.1,141.3,5.96,2.34],[10,96.4,None,15.3,118.4,14.91,2.79]]
random=[[r[0],s,*r[2:]] for r,s in zip(paired,[96.8,97.3,96.8,97,97,96.8])]
PAPERS[1]['cache']=[dict(name='π0.5 · Paired',N=10,source=B('IEIE 표 2·4 · 평균 표준편차 미보고','IEIE Tables 2, 4 · std of the average not reported'),rows=paired),dict(name='π0.5 · Random',N=10,source=B('IEIE 표 2·4 · 평균 표준편차 미보고','IEIE Tables 2, 4 · std of the average not reported'),rows=random),dict(name='GR00T-N1.7 · Paired',N=4,source=B('IEIE 표 3·4 · 평균 표준편차 미보고','IEIE Tables 3, 4 · std of the average not reported'),rows=[[1,97,None,101.1,148,1,1],[2,97,None,47.4,89.7,2.13,1.65],[4,95.8,None,25.2,67.4,4.01,2.19]])]
for dataset,base,types,small,exposure in [
 ('R2R-CE',['NaVILA',5.26,61.4,54,49.3],[['Black patch',5.53,61,51.2,46.4],['Gaussian init',5.48,60.7,51,46.3],['Learned patch',6.89,53,38.6,33.3]],['38 × 38',6.39,56.2,46.8,38.7],[['Initial 10 steps',6.44,54.2,45.8,40.7],['Frequency 8',5.92,58.8,50.4,45.5]]),
 ('RxR-CE',['NaVILA',6.17,61.3,52.1,45.8],[['Black patch',6.32,59.8,50.4,44.1],['Gaussian init',6.23,59.9,48.8,43.8],['Learned patch',7.67,50.9,39.8,35.6]],['38 × 38',6.96,57.4,46.8,38.8],[['Initial 10 steps',6.98,55.3,46.3,39.8],['Frequency 8',6.37,58.8,50.4,44.9]])]:
 for n,(name,rows) in enumerate([(B('생성 방식','Construction'),[base,*types]),(B('크기','Size'),[base,small,['57 × 57',*types[-1][1:]]]),(B('노출','Exposure'),[base,['Ideal',*types[-1][1:]],*exposure])],1):
  PAPERS[3]['studies'].append(study(B(dataset+' · '+name['ko'],dataset+' · '+name['en']),['NE (m) ↓','OS (%) ↑','SR (%) ↑','SPL (%) ↑'],rows,B(f'원문 표 {n} · Val-Unseen · 화살표는 주행 정책 관점의 좋은 방향',f'Table {n} · Val-Unseen · arrows indicate better navigation'),'mixed',100,1))
for p in PAPERS:
 p.setdefault('code',None)
 p['formal_title']=p['title']['en'] if p['slug']!='endcache' else p['title']['en']+' '+p['subtitle']['en']
 kind='misc' if p['slug']=='endcache' else 'inproceedings'
 venue='' if kind=='misc' else f'  booktitle={{{p["bibvenue"]}}},\n'
 note='  note={Author-provided manuscript; publication identifiers omitted},\n' if kind=='misc' else ''
 p['bibtex']=f'@{kind}{{kim{p["year"]}{p["slug"].replace("-","")},\n  title={{{p["formal_title"]}}},\n  author={{{p["bibauthors"]}}},\n{venue}{note}  year={{{p["year"]}}}\n}}'
 if p['slug']=='star':p['bibtex']=p['bibtex'].replace('kim2026star','sung2026star')
