'use strict';
(()=>{
const lang=document.documentElement.lang==='ko'?'ko':'en',ko=lang==='ko';
const t=(a,b)=>ko?a:b,L=v=>v&&typeof v==='object'&&!Array.isArray(v)?v[lang]:v;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=(n,d=1)=>Number(n).toFixed(d),signed=n=>(n>0?'+':'')+fmt(n);
const select=(id,label,opts)=>`<div class="control"><label for="${id}">${esc(label)}</label><select id="${id}">${opts.map((v,i)=>`<option value="${i}">${esc(L(v))}</option>`).join('')}</select></div>`;
const readout=(label,value,note='')=>`<div class="readout"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`;
function bars(rows,max=100,unit='%',digits=1){return rows.map(r=>`<div class="bar-row"><span class="bar-label">${esc(L(r[0]))}</span><div class="track" aria-hidden="true"><div class="fill" style="--value:${Math.max(0,Math.min(100,Number(r[1])/max*100))}%"></div></div><span class="value">${fmt(r[1],digits)}${esc(unit)}</span></div>`).join('')+`<p class="plot-caption">${t('축 범위','Axis range')}: 0–${max}${esc(unit)}</p>`;}
qa('.language').forEach(a=>a.addEventListener('click',()=>{try{localStorage.setItem('research-language',a.hreflang);}catch(_){}const url=new URL(a.href,location.href);url.hash=location.hash;a.href=url.href;}));
const data=q('#paper-data'),p=data?JSON.parse(data.textContent):null;
if(p){
 const root=q('#explorer');
 root.innerHTML=`<div class="exp-head"><strong>${t('결과 탐색기','Results explorer')}</strong><p>${t('원문 실험값 기반 · 실제 모델 추론 아님','Reported experimental values · not live model inference')}</p></div><div class="exp-body" id="exp-body"></div>`;
 try{const body=q('#exp-body');if(p.kind==='cache')cache(body);else if(p.kind==='film')film(body);else studies(body);}catch(e){q('#exp-body').textContent=t('탐색기를 불러오지 못했습니다. 아래 전체 결과 표를 확인해 주세요.','The explorer could not load. Please use the full result tables below.');console.error(e);}
}
function cache(root){
 root.innerHTML=`<div class="controls">${select('cache-model',t('모델 · 평가 조건','Model · evaluation'),p.cache.map(m=>m.name))}<div class="control"><label for="cache-k">${t('재사용 간격','Reuse interval')} k</label><div class="range-line"><input id="cache-k" type="range" min="0" max="5" step="1" value="0"><output id="cache-k-output" for="cache-k"></output></div><div id="k-ticks" class="k-ticks" aria-hidden="true"></div></div></div><div id="cache-values" class="readouts" aria-live="polite"></div><div class="plot-heading">${t('생성 단계별 모델 호출 위치','Model calls across generation steps')}</div><div class="schedule" id="schedule" aria-hidden="true"></div><p class="legend">${t('채워진 칸: 새 계산 · 점선 칸: 캐시 재사용 후 상태 갱신','Filled: fresh evaluation · Dashed: cached output with a state update')}</p><div class="plot-heading">${t('전체 모델 추론 지연','Whole-model inference latency')}</div><div id="cache-plot"></div><div id="cache-note" class="explanation"></div><p id="cache-source" class="source"></p>`;
 const m=q('#cache-model'),k=q('#cache-k');
 function reset(){const model=p.cache[Number(m.value)];k.max=model.rows.length-1;k.value=model.rows.length-1;q('#k-ticks').innerHTML=model.rows.map(r=>`<span>${r[0]}</span>`).join('');draw();}
 function draw(){const model=p.cache[Number(m.value)],r=model.rows[Number(k.value)],b=model.rows[0],N=model.N,nfe=Math.ceil(N/r[0]);
 q('#cache-k-output').textContent=`k = ${r[0]}`;k.setAttribute('aria-valuetext',`${t('재사용 간격','Reuse interval')} ${r[0]}`);
 q('#cache-values').innerHTML=readout(t('모델 호출 수 · 계산값','Calls · calculated'),`${N} → ${nfe}`,`ceil(${N} / ${r[0]})`)+readout(t('평균 과업 성공률','Mean task success'),`${fmt(r[1])}%`,r[2]===null?t('평균 표준편차 미보고','Std of mean not reported'):`± ${fmt(r[2])} pp`)+readout(t('전체 모델 지연','Whole-model latency'),`${fmt(r[4])} ms`,`${fmt(r[6],2)}× ${t('실측 가속','measured speedup')}`);
 q('#schedule').innerHTML=Array.from({length:N},(_,i)=>`<span class="tick ${i%r[0]===0?'fresh':''}">${i}</span>`).join('');
 q('#cache-plot').innerHTML=bars([[t('기준 · k=1','Baseline · k=1'),b[4]],[`k=${r[0]}`,r[4]]],b[4],' ms');
 q('#cache-note').textContent=t(`성공률 변화 ${signed(r[1]-b[1])} pp. 행동 생성기 지연은 ${fmt(r[3])} ms (${fmt(r[5],2)}×), 전체 모델 가속은 ${fmt(r[6],2)}×입니다. 호출 수 감소와 시간 가속은 다릅니다. 스케줄은 알고리즘의 호출 위치를 설명하며 로봇 동작 영상이 아닙니다.`,`Success change: ${signed(r[1]-b[1])} pp. Action-generator latency is ${fmt(r[3])} ms (${fmt(r[5],2)}×); whole-model speedup is ${fmt(r[6],2)}×. Call-count and time speedup are distinct. The schedule explains calls, not robot motion.`);
 q('#cache-source').textContent=L(model.source);
 }
 m.addEventListener('change',reset);k.addEventListener('input',draw);reset();
 if(p.slug==='endcache'){const s=p.studies[0];root.insertAdjacentHTML('beforeend',`<div class="plot-heading">${t('같은 예산에서 무엇을 재사용할까?','What should be reused at the same budget?')}</div>${bars(s.rows)}<p class="source">${esc(L(s.source))}</p>`);}
}
function studies(root){
 root.innerHTML=`<div class="controls">${select('study-select',t('비교 실험','Study'),p.studies.map(s=>s.title))}${select('metric-select',t('평가 지표','Metric'),[])}</div><div id="study-plot" aria-live="polite"></div><p id="study-source" class="source"></p><div id="study-note" class="explanation"></div>`;
 function reset(){const s=p.studies[Number(q('#study-select').value)];q('#metric-select').innerHTML=s.cols.map((c,i)=>`<option value="${i}">${esc(L(c))}</option>`).join('');if(p.slug==='navila-patch')q('#metric-select').value='2';else if(p.slug==='star'&&q('#study-select').value==='0')q('#metric-select').value='3';draw();}
 function draw(){const s=p.studies[Number(q('#study-select').value)],i=Number(q('#metric-select').value),mixed=s.unit==='mixed',max=mixed&&i===0?10:s.maximum,unit=mixed?(i===0?' m':'%'):s.unit,digits=mixed&&i===0?2:s.digits;
 q('#study-plot').innerHTML=bars(s.rows.filter(r=>r[i+1]!==null).map(r=>[r[0],r[i+1]]),max,unit,digits);q('#study-source').textContent=L(s.source);
 q('#study-note').textContent=p.slug==='navila-patch'?t('NE는 낮을수록, OS·SR·SPL은 높을수록 주행 정책의 성능이 좋습니다. 성능 저하를 별도의 공격 성공률로 표시하지 않습니다. 패치 크기·노출 조건은 각 표의 독립 실험입니다.','Lower NE and higher OS/SR/SPL indicate better navigation. Degradation is not presented as a separate attack success rate. Patch size and exposure are independent studies.'):p.slug==='star'?t('T: 시간 유사도 · S: 공간 유사도 · C: 유형 정확도 · ACCS: 통합 점수. 구성명 속 T/S/C는 각 과업의 LoRA 여부입니다. 모든 지표는 높을수록 좋습니다.','T: temporal similarity · S: spatial similarity · C: type accuracy · ACCS: unified score. T/S/C in configuration names denote task-specific adapters. Higher is better.'):t('같은 시연 데이터의 비교입니다. 채널만 사용한 경우 성공률은 두 과업 모두 기준 ACT보다 낮습니다. 매개변수는 전체 모델 크기가 아니라 학습 가능한 부분을 센 값입니다.','Comparisons use the same demonstrations. Channel-only success is below ACT on both tasks. Parameter counts refer to trainable parameters, not total model size.');}
 q('#study-select').addEventListener('change',reset);q('#metric-select').addEventListener('change',draw);reset();
}
function film(root){const s=p.studies[0];
 root.innerHTML=`<div class="controls">${select('film-task',t('과업','Task'),s.rows.map(r=>r[0]))}</div><div id="film-plot" aria-live="polite"></div><div id="film-note" class="explanation"></div><p class="source">${esc(L(s.source))}</p><div class="film-toy"><span class="toy-label">${t('설명용 산술 예시 · 실제 모델 활성값 아님','Illustrative arithmetic · not learned activations')}</span><div class="equation">H′ = γ ⊙ H + β</div><p class="note">H = [0.20, 0.50, 0.80]. ${t('단순화를 위해 모든 차원에 같은 γ·β를 적용합니다. 실제 모델의 매개변수는 텍스트 임베딩으로부터 학습됩니다.','For simplicity, all dimensions share γ and β. Actual model parameters are learned from text embeddings.')}</p><div class="controls"><div class="control"><label for="film-gamma">γ · ${t('스케일','scale')}</label><div class="range-line"><input id="film-gamma" type="range" min="0" max="2" step="0.05" value="1"><output id="gamma-value" for="film-gamma">1.00</output></div></div><div class="control"><label for="film-beta">β · ${t('시프트','shift')}</label><div class="range-line"><input id="film-beta" type="range" min="-1" max="1" step="0.05" value="0"><output id="beta-value" for="film-beta">0.00</output></div></div></div><div class="vector" id="film-vector" aria-live="polite"></div></div>`;
 function draw(){const r=s.rows[Number(q('#film-task').value)],rows=s.cols.map((name,i)=>[name,r[i+1]]).filter(r=>r[1]!==null);q('#film-plot').innerHTML=bars(rows)+(r[3]===null?`<p class="missing">${t('상세 지시문: 이 과업의 결과는 원문에 보고되지 않았습니다.','Detailed instruction: no result is reported for this task.')}</p>`:'');q('#film-note').textContent=r[0]==='sweep into'?t('기본 “Sweep a puck into a hole.” → 상세 “Grasp the puck and sweep it into the hole in front of it.” 기본 조건은 74% → 72%로 하락하고, 상세 조건은 82%입니다.','Basic: “Sweep a puck into a hole.” → Detailed: “Grasp the puck and sweep it into the hole in front of it.” Basic success falls from 74% to 72%, while detailed success is 82%.'):t(`기본 지시문 변화: ${signed(r[2]-r[1])} pp. 상세 지시문 결과는 네 과업에서만 보고되어 있습니다.`,`Basic-instruction change: ${signed(r[2]-r[1])} pp. Detailed-instruction results are reported on only four tasks.`);}
 function toy(){const g=Number(q('#film-gamma').value),b=Number(q('#film-beta').value);q('#gamma-value').textContent=fmt(g,2);q('#beta-value').textContent=fmt(b,2);q('#film-vector').innerHTML=[.2,.5,.8].map(h=>`<span>${fmt(g*h+b,2)}</span>`).join('');}
 q('#film-task').value='7';q('#film-task').addEventListener('change',draw);q('#film-gamma').addEventListener('input',toy);q('#film-beta').addEventListener('input',toy);draw();toy();
}
const copy=q('#copy');if(copy)copy.addEventListener('click',async()=>{const text=q('#bibtex').textContent;let ok=false;try{if(navigator.clipboard){await navigator.clipboard.writeText(text);ok=true;}}catch(_){}if(!ok){const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.top='-1000px';document.body.appendChild(a);a.select();try{ok=document.execCommand('copy');}catch(_){}a.remove();copy.focus();}q('#copy-status').textContent=ok?t('인용 정보를 복사했습니다.','Citation copied.'):t('자동 복사가 제한되어 있습니다. 아래 인용문을 직접 선택해 복사해 주세요.','Automatic copying is restricted. Select and copy the citation directly.');});
const zoom=q('.zoom'),dialog=q('#figure-dialog');if(zoom&&dialog){zoom.addEventListener('click',()=>{q('img',dialog).src=q('img',zoom).src;dialog.showModal();});q('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});}
const search=q('#search');if(search){let category='all';function filter(){let n=0;qa('.card').forEach(c=>{const show=(category==='all'||c.dataset.category===category)&&c.dataset.search.includes(search.value.trim().toLowerCase());c.hidden=!show;if(show)n++;});q('#result-count').textContent=t(`${n}편의 논문`,`${n} papers`);q('#empty').hidden=n!==0;}qa('.filter').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;qa('.filter').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));search.addEventListener('input',filter);}
})();
